# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-controller:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-resolvers:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-webhook:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-kubeconfigwriter:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-git-init:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-entrypoint:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-nop:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-imagedigestexporter:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-pullrequest-init:v0.43.2
        skopeo copy --all docker://ghcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.43.2 docker://docker.io/shangshan/tektoncd-pipeline-workingdirinit:v0.43.2

 
